<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>amazon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ae62e918-538b-4b0d-8ab4-e551fee704ba</testSuiteGuid>
   <testCaseLink>
      <guid>a2fa2312-aee2-4244-8976-e63e936bcd8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmazonProject/TC_Amazon_Home_SV_003</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e6558004-eb92-4465-b899-e3ecf445eb2f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT_TestData/Amazon_Search_excel_folder</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e6558004-eb92-4465-b899-e3ecf445eb2f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>8da9dc91-9fb4-4f81-9519-8e886bcec16a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e6558004-eb92-4465-b899-e3ecf445eb2f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>99393b23-cf64-487b-8f26-df8f45d08007</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
